SOFDEC_FILES :=\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/cft/srcgc/cftyp422_ppc.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/cft/cft_common.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdfrm.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdrna.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdrsc.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdsl.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdsvm.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwstm.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdsee.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdsfx.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdcre.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdlib.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdply.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdset.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdsvr.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfdsst.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/mwsfx_Y84C44.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/mwply/code_803A3AE4.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_bdec.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_cdec.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_cmc.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_dec.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_deli.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_emp.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_err.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_frm.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_get.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_hdec.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_lib.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_mc.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_vlc.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_umc.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_mcy.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_m2v.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpvabdec.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mpv/mpv_slice.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/dct/dct_ac.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/dct/dct_isr.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/dct/dct_ver.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/memcpy/mcp_not.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mps/mps_dec.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mps/mps_del.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mps/mps_get.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/mps/mps_lib.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_adxt.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_aoap.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_buf.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/code_803BFD20.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_con.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_hds.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_lib.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_mem.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_mps.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_mpv.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_mpvf.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_pl2.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_ply.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_pts.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_see.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_set.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_tim.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_trn.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_uo.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_vom.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_tmr.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_tst.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfd/sfd_seeki.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfh/sfh_local.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfh/sfh_main.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfh/sfh_ver1.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/sfh/sfh_ver2.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/uty/cmptime.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/uty/memcpyd.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/uty/memsetd.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/uty/muldiv.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/uty/muldivr.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfdcore/uty/uty_tmr.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfx/sfx_set.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfx/sfx_cnv.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfx/sfx_inf.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfx/sfx_lib.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfx/sfx_alp.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfx/sfx_zmv.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfx/sfx_sud.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sfx/sfx_cnv_to_Y84C44.o\
	$(BUILD_DIR)/libs/CriWare/asm/sofdec/sud/sud_lib.o\

DEPENDS += $(SOFDEC_FILES:.o=.d)

$(BUILD_DIR)/libs/CriWare/src/sofdec/libmwsfdwii.a: $(SOFDEC_FILES)
	@echo Linking... $@
	$(QUIET) mkdir -p $(dir $@)
	@echo $(SOFDEC_FILES) > build/SOFDEC_ofiles
	$(QUIET) $(LD) -library $(LIBRARY_LDFLAGS) -o $@ -lcf ldscript.lcf @build/SOFDEC_ofiles
