#pragma once

#include "monolib/vm/yvm_types.h"

//Utility functions/macros

//Q20.12 fixed point macros (20 integer bits, 12 fraction bits)
#define FIXED_TO_INT(x) ((x) >> 12)
#define INT_TO_FIXED(x) ((x) << 12)

//Utility pointer functions

static inline void* getSectionEntriesPtr(SBSectionHeader* header){
    return (void*)((u32)header + header->entriesOffset);
}

static inline void* getRelativePtr(void* header){
    return (void*)((u32)header + *(u32*)header);
}

static inline void adjustSectionPtr(void* pBase, void* pPtr){
    *(u8**)pPtr += (u32)pBase;
}

/* TODO: Maybe this is autogenerated by mwcc?? It doesn't make sense that they would
only access the struct values differently here, but mwcc seems to only want to
copy with lwz/stw
The volatile also is probably fake */
static inline void copyArg(VMArg* lhs, volatile VMArg* rhs){
    lhs->type = rhs->type;
    lhs->unk1 = rhs->unk1;
    *(u32*)&lhs->unk2 = *(u32*)&rhs->unk2;
    *(u16*)((u32)lhs + 6) = *(u16*)((u32)rhs + 6);
}

static inline void saveArg(VMThread* pThread, VMArg* pArg, int index){
    copyArg(&pThread->unk14[index], pArg);
}

static inline void setThreadSleepFlag(VMThread* pThread, BOOL state){
    if(state == TRUE) pThread->unk48 |= 0x80000000;
    else pThread->unk48 &= ~0x80000000;
}
