GAME_O_FILES :=\
	$(BUILD_DIR)/asm/kyoshin/appgame/CGame.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/IWorkEvent.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CGameRestart.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/main_1.o \
	$(BUILD_DIR)/src/kyoshin/appgame/main.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/main_2.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_8003A53C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTaskGame.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CTaskGameCf.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTaskGameEff.o \
	$(BUILD_DIR)/asm/kyoshin/action/CActParamAnim.o \
	$(BUILD_DIR)/asm/kyoshin/action/CActParamData.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CMcaFile.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CTaskEnvironment.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTimeLightGrp.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CActParamAnimGame.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_800602B4.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CTaskGameEffAfter.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfResTask.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfRes.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/IResInfo.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfScript.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfTaskMain.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfTFile.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCamEvent.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCamDirectionIntf.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCamLookatIntf.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCamTargetIntf.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCam.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCamFollow.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_80074F4C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_8007C0F8.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlEnemy.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlMoveBase.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlEneAiCall.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlMoveEne.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlNpc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlPad.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlPc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlRemote.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlObjectParam.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_8009ED08.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_800AA008.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCollCircleImpl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCollSphereImpl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCollAABBImpl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCollCylinderImpl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfCollCapsuleImpl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectColl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectEff.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectEne.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectMap.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectModel.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectMove.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectNpc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectObj.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectPc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectPoint.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectImplWalker.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectImplPc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectImplObj.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectImplNpc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectImplMove.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectImplEne.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlAct.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_800D7A04.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CBattleManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectEnumList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectSelectorObj.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CMainMenu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CMainCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuArtsSelect.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuBattleDamage.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuBattlePlayerState.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CPcSelectCursor.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuEnemyState.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuFade.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuKeyAssign.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CMiniMap.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CMMClock.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuQuestLog.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuSymbolMark.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CArrow3D.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CQuestWindow.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSystemWindow.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSysWinSelect.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTagProcessor.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTalkWindow.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CUIBattleManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CUICfManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CUIWindowManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfBdat.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuUpdate.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuLandTelop.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CBattleState.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuGetItem.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_8014A864.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CAIAction.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CArtsSet.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CArtsParam.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CItem.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CCharEffect.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CCharEffectEne.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CCol6CheckBat.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CCol6System.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CCol6Invite.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CTaskREvent.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CInfoCf.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuItem.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtMem.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CTaskREvtSequence.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfResObjImpl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfResReloadImpl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfMapEffectManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectActor.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtModel.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfMapItemManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CActorParam.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuZeal.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtCamera.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtModelMap.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtModelObj.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtModelPc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtEffect.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtObj.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuPTGauge.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuSelectShop.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuShopSell.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuShopBuy.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfResPcImpl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuPTState.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CPartsChange.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlMovePC.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CtrlMoveNpc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuBattleMode.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/COccCulling.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSimpleEveTalkWin.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CTaskCulling.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CVision.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuVision.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuBattleCommu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CPcEffect07.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuGetItemMulti.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CSuddenCommu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuKizunaTalk.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuItemExchange.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfPadTask.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtLight.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CBgTex.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTitleAHelp.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CQuestItem.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CVisionItem.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CArtsBookItem.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CItemBoxGrid.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSortMenu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CItemBoxInfo.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CItemBoxInfo2.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CNumSelect.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CIBLTabCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CItemBoxLine.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CScrollBar.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfGimmickObject.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfObjectTbox.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfResTboxImpl.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CPartyStateWin.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CModelDisp.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CPartyState.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/parts/CModelDispEquip.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CEquipChange.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfMapMineManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CItemBoxGridSubMenu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfGimmick.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfGimmickElv.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfGimmickLock.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfGimmickWarp.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfGimmickJump.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfGimmickItem.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMenuMakeCrystal.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMakeCrystalWin.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCCrystalBox.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCCrystalInfo.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CModelDispMakeCrystal.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCCylinderGauge.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCCrystalList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffStart.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffUpRed.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffUpBlue.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffUpGreen.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffUpPrm.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffSuccess.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffFailure.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffCrystal.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffUpRank.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffDivide.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCEffCylinder.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuQstCnt.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CQstLogList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CQstLogInfo.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSysWin.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSelShopWin.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CExchangeWin.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CPresentWin.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCCrystalSupport.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuArtsSet.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CArtsList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CArtsInfo.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfNandManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_802405F4.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuMapSelect.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CMapSel.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CFade.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_80244F50.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CFloorMap.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuMapSelectSC.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuPause.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuCollepedia.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CCLPCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CCollepedia.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuKizunagram.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CKizunaRadar.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CKizunaCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CKizunaLine.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CKizunaInfo.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CKizunagram.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CPcKizunaCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CPcKizunagram.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuPassiveSkill.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/UI/CPassiveSkillCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/UI/CPassiveSkillInfo.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/UI/CPassiveSkillLine.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/UI/CPassiveSkill.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfGimmickEne.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuBattleEnd.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuPlayAward.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CPlayAwardList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuKizunaTalkList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CKizunaTalkList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSysWinBuff.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/ICamControlRemote.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/ICamControlGc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/ICamControlClassic.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_8027513C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuLvUp.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/chain/CChainActor.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/chain/CChainActorList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/chain/CChainTime.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/chain/CChainTimer.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSysWinScenarioLog.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/chain/CChainActorEne.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/chain/CChainActorPc.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CEquipItemBox.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CEIBCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CEIBPageCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CEquipItemBox_1.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuSave.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSLCur.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSaveLoad.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuPTChangeNotice.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/chain/CChainCombo.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSysWinSave.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/realtimeevt/CREvtMovie.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTaskGamePic.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTaskGameEvt.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CHelpManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_80296898.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_80296B44.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/makecrystal/CMCGetItemBox.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuTutorial.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTutorial.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuOption.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CCur19.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/COption.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuSkipTimer.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSkipTimer2.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CSkipTimer.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/chain/CChainEffect.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CCharVoice.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CCharVoiceMan.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_BATTLE_END.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_BUF.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_CHAIN.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_DOWN.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_EHP.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_FAINT.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_HAGE.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_HP.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_PARTY_GAGE.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_REVIVE.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_SUDDEN.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_TENSION_UP.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_VISION_BREAK.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_VISION_TELL.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuBattleChain.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_BATTLE_END_SP.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfGimmickSaveOff.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuTutorialList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTutorialList.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CLoad.o \
	$(BUILD_DIR)/src/kyoshin/appgame/code_802AEB74.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/code_802AEBC4.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_BATTLE_MAIN.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_BATTLE_BEGIN.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuGCItem.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuGameClear.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfHikariItemManager.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CUIErrMesWin.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/menu/CMenuTitle.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTitleLogo.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTitleMenu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CTitle.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_ArtsAttack.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_ArtsSet.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_CkKizuna.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_CloseItemMenu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_CloseSysMenu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_EndEvent.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_EnemyCount.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_EnemyEnable.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_EtherMake.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_Exchange.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_GameOver.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_ItemCole.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_Kizuna.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_LandMark.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_LearnArts.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_ClosePartyMenu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_OpenPartyMenu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_Pg.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_CloseQuestMenu.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_ShopBuy.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_ShopSel.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_Sp.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_Talk.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/help/CHelp_Target.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/voice/CVS/CVS_THREAD_ORDER.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/CBattery.o \


MW_O_FILES :=\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/__mem.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/__exception.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/strlen.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/__va_arg.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/global_destructor_chain.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/NMWException.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/ptmf.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/MWRTTI.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/runtime.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/__init_cpp_exceptions.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/Gecko_ExceptionPPC.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/GCN_mem_alloc.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/alloc.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/ansi_files.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/ansi_fp.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/arith.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/assert.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/buffer_io.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/direct_io.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/errno.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/file_io.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/file_pos.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/mbstring.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/mem.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/mem_funcs.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/math_api.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/misc_io.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/printf.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/rand.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/float.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/scanf.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/signal.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/string.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/strtold.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/strtoul.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wcstoul.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wmem.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wprintf.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wscanf.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wstring.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wchar_io.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/PPC_EABI/uart_console_io_gcn.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/PPC_EABI/abort_exit_ppc_eabi.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/math_double.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/math_sun.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_acos.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_asin.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_atan2.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_fmod.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_log.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_log10.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_pow.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_rem_pio2.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/k_cos.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/k_rem_pio2.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/k_sin.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/k_tan.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_atan.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_ceil.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_copysign.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_cos.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_floor.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_frexp.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_ldexp.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_modf.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_sin.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_tan.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_acos.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_asin.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_atan2.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_fmod.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_log.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_log10.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_pow.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_sqrt.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/PPC_EABI/math_ppc.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_sqrt.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/extras.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/targsupp.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/main.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/custconn/MWCriticalSection_gc.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/custconn/CircleBuffer.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/flush_cache.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/main_TRK.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/mainloop.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/mem_TRK.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MetroTRK/dispatch.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/dolphin_trk.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/dolphin_trk_glue.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/notify.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/nubevent.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/nubinit.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/serpoll.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/string_TRK.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/support.o \
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MetroTRK/targcont.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/mpc_7xx_603e.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/msg.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/msgbuf.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/msghndlr.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/mslsupp.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/targimpl.o \
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/target_options.o \

NDEV_O_FILES :=\
	$(BUILD_DIR)/src/NdevExi2A/DebuggerDriver.o \
	$(BUILD_DIR)/src/NdevExi2A/exi2.o \

RVL_SDK_O_FILES :=\
	$(BUILD_DIR)/asm/RevoSDK/ai/ai.o \
	$(BUILD_DIR)/src/RevoSDK/arc/arc.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AX.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXAlloc.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXAux.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXCL.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXOut.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXSPB.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXVPB.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXProf.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXReverbHi.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXReverbHiExp.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXDelayExp.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXDelayExpDpl2.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXReverbStdExp.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXReverbStdExpDpl2.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXChorusExp.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXChorusExpDpl2.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXLfoTable.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXSrcCoef.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXHooks.o \
	$(BUILD_DIR)/src/RevoSDK/base/PPCArch.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gki_buffer.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gki_time.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gki_ppc.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hcisu_h2.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/uusb_ppc.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bte_hcisu.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bte_init.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bte_logmsg.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bte_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btu_task1.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bd.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_sys_conn.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_sys_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/ptim.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/utl.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_dm_act.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_dm_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_dm_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_dm_pm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_hh_act.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_hh_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_hh_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_hh_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_acl.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_dev.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_devctl.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_discovery.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_inq.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_pm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_sco.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_sec.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btu_hcif.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btu_init.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/wbt_ext.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gap_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gap_conn.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gap_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hcicmds.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidd_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidd_conn.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidd_mgmt.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidd_pm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidh_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidh_conn.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_csm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_link.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/port_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/port_rfc.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/port_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_l2cap_if.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_mx_fsm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_port_fsm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_port_if.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_ts_frames.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_db.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_discovery.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_server.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/cx/CXStreamingUncompression.o \
	$(BUILD_DIR)/asm/RevoSDK/cx/CXUncompression.o \
	$(BUILD_DIR)/src/RevoSDK/cx/CXSecureUncompression.o \
	$(BUILD_DIR)/asm/RevoSDK/db/db.o \
	$(BUILD_DIR)/asm/RevoSDK/dsp/dsp.o \
	$(BUILD_DIR)/asm/RevoSDK/dsp/dsp_debug.o \
	$(BUILD_DIR)/asm/RevoSDK/dsp/dsp_task.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdfs.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvd.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdqueue.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvderror.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdidutils.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdFatal.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdDeviceError.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvd_broadway.o \
	$(BUILD_DIR)/asm/RevoSDK/enc/encutility.o \
	$(BUILD_DIR)/asm/RevoSDK/enc/enc.o \
	$(BUILD_DIR)/asm/RevoSDK/esp/esp.o \
	$(BUILD_DIR)/asm/RevoSDK/euart/euart.o \
	$(BUILD_DIR)/asm/RevoSDK/exi/EXIBios.o \
	$(BUILD_DIR)/asm/RevoSDK/exi/EXIUart.o \
	$(BUILD_DIR)/asm/RevoSDK/exi/EXICommon.o \
	$(BUILD_DIR)/asm/RevoSDK/fs/fs.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXInit.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXFifo.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXAttr.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXMisc.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXGeometry.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXFrameBuf.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXLight.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXTexture.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXBump.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXTev.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXPixel.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXDisplayList.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXTransform.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXPerf.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMFrameController.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMAnmController.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMGUIManager.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMController.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMRemoteSpk.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMAxSound.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMBase.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_animation.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_arcResourceAccessor.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_bounding.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_common.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_drawInfo.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_group.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_layout.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_material.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_pane.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_picture.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_resourceAccessor.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_textBox.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_window.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/math/math_triangular.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_binaryFileFormat.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_CharWriter.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_Font.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_LinkList.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_list.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_ResFont.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_ResFontBase.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_TagProcessorBase.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_TextWriterBase.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/mix.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/syn.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synctrl.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synenv.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synmix.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synpitch.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synsample.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synvoice.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/seq.o \
	$(BUILD_DIR)/asm/RevoSDK/ipc/ipcMain.o \
	$(BUILD_DIR)/asm/RevoSDK/ipc/ipcclt.o \
	$(BUILD_DIR)/asm/RevoSDK/ipc/memory.o \
	$(BUILD_DIR)/asm/RevoSDK/ipc/ipcProfile.o \
	$(BUILD_DIR)/asm/RevoSDK/kpad/kpad.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_heapCommon.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_expHeap.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_frameHeap.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_allocator.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_list.o \
	$(BUILD_DIR)/asm/RevoSDK/mix/mix.o \
	$(BUILD_DIR)/asm/RevoSDK/mix/remote.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/mtx.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/mtxvec.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/mtx44.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/vec.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/quat.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/nand.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/NANDOpenClose.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/NANDCore.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/NANDCheck.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/NANDLogging.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OS.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSAlarm.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSAlloc.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSArena.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSAudioSystem.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSCache.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSContext.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSError.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSExec.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSFatal.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSFont.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSInterrupt.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSMessage.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSMemory.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSMutex.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSReboot.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSReset.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSRtc.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSSync.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSThread.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSTime.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSUtf.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSIpc.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSStateTM.o \
	$(BUILD_DIR)/src/RevoSDK/os/__start.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSPlayRecord.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSStateFlags.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSNet.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSNandbootInfo.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSPlayTime.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSCrc.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSLaunch.o \
	$(BUILD_DIR)/asm/RevoSDK/os/__ppc_eabi_init.o \
	$(BUILD_DIR)/asm/RevoSDK/pad/Pad.o \
	$(BUILD_DIR)/asm/RevoSDK/sc/scsystem.o \
	$(BUILD_DIR)/asm/RevoSDK/sc/scapi.o \
	$(BUILD_DIR)/asm/RevoSDK/sc/scapi_prdinfo.o \
	$(BUILD_DIR)/asm/RevoSDK/si/SIBios.o \
	$(BUILD_DIR)/asm/RevoSDK/si/SISamplingRate.o \
	$(BUILD_DIR)/asm/RevoSDK/tpl/TPL.o \
	$(BUILD_DIR)/asm/RevoSDK/usb/usb.o \
	$(BUILD_DIR)/asm/RevoSDK/vi/vi.o \
	$(BUILD_DIR)/asm/RevoSDK/vi/i2c.o \
	$(BUILD_DIR)/asm/RevoSDK/vi/vi3in1.o \
	$(BUILD_DIR)/asm/RevoSDK/wenc/wenc.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/WPAD.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/WPADHIDParser.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/WPADEncrypt.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/WPADMem.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/debug_msg.o \
	$(BUILD_DIR)/asm/RevoSDK/wud/WUD.o \
	$(BUILD_DIR)/asm/RevoSDK/wud/WUDHidHost.o \
	$(BUILD_DIR)/asm/RevoSDK/wud/debug_msg.o

CRIWARE_O_FILES :=\
	$(BUILD_DIR)/asm/CriWare/adx/adxf/adx_fini.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxf/adx_fs.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxf/adx_fcch.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_fsvr.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_inis.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_lsc.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_mng.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_sfa.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_sjd.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_stmc.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_tlk2.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_tlk.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_tsvr.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_xpnd.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_amp.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_bahx.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_baif.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_bsc.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_bwav.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/code_80389300.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_crs.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_dcd5.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_dcd.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_errs.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_ftbl.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_link.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_mflt_c.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_mwin2_c.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_sbf2.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_sbf.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_sjd.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_wtbl.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/adx_hdr.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_bsr.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_cmn.o \
	$(BUILD_DIR)/asm/CriWare/adx/ahx/ahx_dcd.o \
	$(BUILD_DIR)/asm/CriWare/adx/cricfg/cfg_lib.o \
	$(BUILD_DIR)/asm/CriWare/adx/cvfs/cri_cvfs.o \
	$(BUILD_DIR)/asm/CriWare/adx/gcci/gcci.o \
	$(BUILD_DIR)/asm/CriWare/adx/gcci/gcci_sub.o \
	$(BUILD_DIR)/asm/CriWare/adx/lsc/lsc_err.o \
	$(BUILD_DIR)/asm/CriWare/adx/lsc/lsc_ini.o \
	$(BUILD_DIR)/asm/CriWare/adx/lsc/lsc_svr.o \
	$(BUILD_DIR)/asm/CriWare/adx/lsc/lsc.o \
	$(BUILD_DIR)/asm/CriWare/adx/lsc/lsc_crs.o \
	$(BUILD_DIR)/asm/CriWare/adx/mfci/mfci.o \
	$(BUILD_DIR)/asm/CriWare/adx/sj/sj_mem.o \
	$(BUILD_DIR)/asm/CriWare/adx/sj/sj_rbf.o \
	$(BUILD_DIR)/asm/CriWare/adx/sj/sj_uni.o \
	$(BUILD_DIR)/asm/CriWare/adx/sj/sj_utl.o \
	$(BUILD_DIR)/asm/CriWare/adx/sj/sj_crs.o \
	$(BUILD_DIR)/asm/CriWare/adx/sj/sj_err.o \
	$(BUILD_DIR)/asm/CriWare/adx/svm/svm.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_bsps.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/adx_bau.o \
	$(BUILD_DIR)/asm/CriWare/adx/wiirna/rna_crs.o \
	$(BUILD_DIR)/asm/CriWare/adx/wiirna/rna_err.o \
	$(BUILD_DIR)/asm/CriWare/adx/wiirna/ax_rna.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/srcwii/adx_mwii.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/srcwii/adx_suwii.o \
	$(BUILD_DIR)/asm/CriWare/adx/adxt/srcwii/adx_rnawii.o \
	$(BUILD_DIR)/asm/CriWare/cri_crw_std.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/cft/srcgc/cftyp422_ppc.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/cft/cft_common.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdfrm.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdrna.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdsl.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdsvm.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwstm.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdsfx.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdcre.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdlib.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdply.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdset.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdsvr.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfdsst.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/mwsfx_Y84C44.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/mwply/code_803A3AE4.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_bdec.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_cdec.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_cmc.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_dec.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_deli.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_emp.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_err.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_frm.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_get.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_hdec.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_lib.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_mc.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_vlc.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_umc.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_mcy.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_m2v.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpvabdec.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mpv/mpv_slice.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/dct/dct_ac.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/dct/dct_isr.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/dct/dct_ver.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/memcpy/mcp_not.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mps/mps_dec.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mps/mps_del.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mps/mps_get.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/mps/mps_lib.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_adxt.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_aoap.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_buf.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_con.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_hds.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_lib.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_mem.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_mps.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_mpv.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_mpvf.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_pl2.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_ply.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_pts.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_see.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_set.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_tim.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_trn.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_uo.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_vom.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_tmr.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_tst.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfd/sfd_seeki.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfh/sfh_main.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfh/sfh_ver1.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/sfh/sfh_ver2.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/uty/cmptime.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/uty/memcpyd.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/uty/memsetd.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/uty/muldiv.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/uty/muldivr.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfdcore/uty/uty_tmr.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfx/sfx_set.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfx/sfx_cnv.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfx/sfx_inf.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfx/sfx_lib.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfx/sfx_alp.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfx/sfx_zmv.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfx/sfx_sud.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sfx/sfx_cnv_to_Y84C44.o \
	$(BUILD_DIR)/asm/CriWare/sofdec/sud/sud_lib.o


NW4R_O_FILES :=\
	$(BUILD_DIR)/asm/nw4r/db/db_console.o \
	$(BUILD_DIR)/asm/nw4r/db/db_assert.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_rescommon.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resdict.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resfile.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resmdl.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resshp.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_restev.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resmat.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resvtx.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_restex.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resnode.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanm.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanmclr.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanmtexpat.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanmtexsrt.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanmchr.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_reslightset.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanmamblight.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanmlight.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanmfog.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanmcamera.o \
	$(BUILD_DIR)/asm/nw4r/g3d/res/g3d_resanmscn.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_transform.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmvis.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmclr.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmtexpat.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmtexsrt.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmchr.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmshp.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmscn.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_obj.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmobj.o \
	$(BUILD_DIR)/asm/nw4r/g3d/platform/g3d_gpu.o \
	$(BUILD_DIR)/asm/nw4r/g3d/platform/g3d_cpu.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_state.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_draw1mat1shp.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_calcview.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_dcc.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_workmem.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_calcworld.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_draw.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_camera.o \
	$(BUILD_DIR)/asm/nw4r/g3d/dcc/g3d_basic.o \
	$(BUILD_DIR)/asm/nw4r/g3d/dcc/g3d_maya.o \
	$(BUILD_DIR)/asm/nw4r/g3d/dcc/g3d_xsi.o \
	$(BUILD_DIR)/asm/nw4r/g3d/dcc/g3d_3dsmax.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnobj.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnroot.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnmdlsmpl.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnmdl.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnmdlexpand.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_calcmaterial.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_init.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnproc.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_fog.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_light.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_calcvtx.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_init.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_pane.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_group.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_layout.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_picture.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_textBox.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_window.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_bounding.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_material.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_texMap.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_drawInfo.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_animation.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_resourceAccessor.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_arcResourceAccessor.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_common.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_util.o \
	$(BUILD_DIR)/asm/nw4r/math/math_arithmetic.o \
	$(BUILD_DIR)/asm/nw4r/math/math_triangular.o \
	$(BUILD_DIR)/asm/nw4r/math/math_types.o \
	$(BUILD_DIR)/asm/nw4r/math/math_geometry.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_AxManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_AxVoice.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_AxVoiceManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_AxfxImpl.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Bank.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_BankFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_BasicPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_BasicSound.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_BiquadFilterPreset.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Channel.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_DisposeCallbackManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_EnvGenerator.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_ExternalSoundPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_FxChorusDpl2.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_FxDelayDpl2.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_FxReverbStdDpl2.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_InstancePool.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Lfo.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_McsSoundArchive.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MemorySoundArchive.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MidiSeqPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MmlParser.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MmlSeqTrack.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MmlSeqTrackAllocator.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_PlayerHeap.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_RemoteSpeaker.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_RemoteSpeakerManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqSound.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqSoundHandle.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqTrack.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundArchive.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundArchiveFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundArchivePlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundHandle.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundStartable.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundSystem.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundThread.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmChannel.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmSound.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmSoundHandle.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Task.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_TaskManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_TaskThread.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Voice.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_VoiceManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Util.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WaveFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WaveSound.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WaveSoundHandle.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WsdFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WsdPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_adpcm.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_LinkList.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_binaryFileFormat.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_CharStrmReader.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_TagProcessorBase.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_IOStream.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_FileStream.o \
	$(BUILD_DIR)/asm/nw4r/ut/code_8042BE14.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_LockedCache.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_Font.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_ResFontBase.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_ResFont.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_ArchiveFontBase.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_PackedFont.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_CharWriter.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_TextWriterBase.o \


MM_O_FILES :=\
	$(BUILD_DIR)/asm/mm/code_80432678.o \
	$(BUILD_DIR)/asm/mm/MemManager.o \
	$(BUILD_DIR)/asm/mm/Operators.o \
	$(BUILD_DIR)/asm/mm/code_80434F94.o \
	$(BUILD_DIR)/asm/mm/MTRand.o \
	$(BUILD_DIR)/asm/mm/Globals1.o \
	$(BUILD_DIR)/asm/mm/code_80435D28.o \
	$(BUILD_DIR)/asm/mm/code_80435DF8.o \
	$(BUILD_DIR)/src/mm/MathConstants.o \
	$(BUILD_DIR)/asm/mm/Random.o \
	$(BUILD_DIR)/asm/mm/code_80436138.o \
	$(BUILD_DIR)/asm/mm/code_80436260.o \
	$(BUILD_DIR)/asm/mm/code_80436E84.o \
	$(BUILD_DIR)/asm/mm/code_80436F20.o \
	$(BUILD_DIR)/asm/mm/code_8043738C.o \

MONOLITHLIB_O_FILES :=\
	$(BUILD_DIR)/asm/monolithlib/work/CWorkThread.o \
	$(BUILD_DIR)/asm/monolithlib/CProc.o \
	$(BUILD_DIR)/asm/monolithlib/CProcRoot.o \
	$(BUILD_DIR)/asm/monolithlib/CRsrcData.o \
	$(BUILD_DIR)/asm/monolithlib/CScriptCode.o \
	$(BUILD_DIR)/asm/monolithlib/CToken.o \
	$(BUILD_DIR)/asm/monolithlib/CRootProc.o \
	$(BUILD_DIR)/asm/monolithlib/CView.o \
	$(BUILD_DIR)/asm/monolithlib/CViewFrame.o \
	$(BUILD_DIR)/asm/monolithlib/CViewRoot.o \
	$(BUILD_DIR)/asm/monolithlib/work/CWorkControl.o \
	$(BUILD_DIR)/asm/monolithlib/work/CWorkFlowSetup.o \
	$(BUILD_DIR)/asm/monolithlib/work/CWorkRoot.o \
	$(BUILD_DIR)/asm/monolithlib/work/CWorkSystem.o \
	$(BUILD_DIR)/asm/monolithlib/work/CWorkSystemMem.o \
	$(BUILD_DIR)/asm/monolithlib/CProcess.o \
	$(BUILD_DIR)/asm/monolithlib/CDoubleListNode.o \
	$(BUILD_DIR)/asm/monolithlib/CChildListNode.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceRemotePad.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceBase.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceSC.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceVI.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceVICb.o \
	$(BUILD_DIR)/asm/monolithlib/CFontLayer.o \
	$(BUILD_DIR)/asm/monolithlib/CGXCache.o \
	$(BUILD_DIR)/asm/monolithlib/IStateCache.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDevice.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceClock.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFile.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFileCri.o \
	$(BUILD_DIR)/src/monolithlib/code_80450B14.o \
	$(BUILD_DIR)/asm/monolithlib/device/code_80450B2C.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFileDvd.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFileJob.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFileJobReadDvd.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFont.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFontInfoExt.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFontInfoRom.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFontLayer.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceFontLoader.o \
	$(BUILD_DIR)/asm/monolithlib/device/CDeviceGX.o \
	$(BUILD_DIR)/asm/monolithlib/CDesktop.o \
	$(BUILD_DIR)/asm/monolithlib/CException.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLib.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLibCri.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLibCriMoviePlay.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLibCriStreamingPlay.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLibG3d.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLibHbm.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLibHbmControl.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLibLayout.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLibStaticData.o \
	$(BUILD_DIR)/asm/monolithlib/lib/CLibVM.o \
	$(BUILD_DIR)/asm/monolithlib/CTaskLOD.o \
	$(BUILD_DIR)/asm/monolithlib/code_804645CC.o \
	$(BUILD_DIR)/asm/monolithlib/code_80468434.o \
	$(BUILD_DIR)/asm/monolithlib/code_8046A530.o \
	$(BUILD_DIR)/asm/monolithlib/LOD/LODMemMan.o \
	$(BUILD_DIR)/asm/monolithlib/mpfsys/MPFDrawDisplayList.o \
	$(BUILD_DIR)/asm/monolithlib/mpfsys/MPFDrawMdlNoColor.o \
	$(BUILD_DIR)/asm/monolithlib/mpfsys/MPFDrawMdlColor.o \
	$(BUILD_DIR)/asm/monolithlib/mpfsys/MPFDrawBillboard.o \
	$(BUILD_DIR)/asm/monolithlib/mpfsys/MPFDrawCross.o \
	$(BUILD_DIR)/asm/monolithlib/mpfsys/MPFDrawBillLayTex.o \
	$(BUILD_DIR)/asm/monolithlib/code_8047CA88.o \
	$(BUILD_DIR)/asm/monolithlib/code_8047D2AC.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnItemCameraNw4r.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnItemId.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnItemLight.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnItemLightNw4r.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnItemModel.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnItemModelNw4r.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnItemPool.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnLightMan.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnMaruShadowNw4r.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnMem.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnRoot.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnRootNw4r.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnTexWorkMan.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnVirtualLight.o \
	$(BUILD_DIR)/asm/monolithlib/code_8049431C.o \
	$(BUILD_DIR)/asm/monolithlib/CVirtualLightAmb.o \
	$(BUILD_DIR)/asm/monolithlib/CVirtualLightDir.o \
	$(BUILD_DIR)/asm/monolithlib/CVirtualLightObj.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScn.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnBlend.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnBloom.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnCameraMan.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnEffectActNw4r.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnFadeMan.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnFilter.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnFilterMan.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnFogMan.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnFrame.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnIdMan.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnItemAnim.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnItemCamera.o \
	$(BUILD_DIR)/asm/monolithlib/code_8049FCAC.o \
	$(BUILD_DIR)/asm/monolithlib/CColiProc.o \
	$(BUILD_DIR)/asm/monolithlib/code_804B2FF0.o \
	$(BUILD_DIR)/asm/monolithlib/code_804B59C8.o \
	$(BUILD_DIR)/asm/monolithlib/code_804BAE10.o \
	$(BUILD_DIR)/asm/monolithlib/code_804BC9EC.o \
	$(BUILD_DIR)/asm/monolithlib/code_804BD8E8.o \
	$(BUILD_DIR)/asm/monolithlib/code_804BF59C.o \
	$(BUILD_DIR)/asm/monolithlib/CLight.o \
	$(BUILD_DIR)/asm/monolithlib/scn/CScnEnvLgtCtrl.o \
	$(BUILD_DIR)/src/monolithlib/Unknown1.o \
	$(BUILD_DIR)/asm/monolithlib/code_804C8684.o \
	$(BUILD_DIR)/asm/monolithlib/code_804C8718.o \
	$(BUILD_DIR)/asm/monolithlib/code_804CC2B8.o \
	$(BUILD_DIR)/asm/monolithlib/effect/CETrail.o \
	$(BUILD_DIR)/asm/monolithlib/work/CWorkSystemCache.o \
	$(BUILD_DIR)/asm/monolithlib/nand/CNand.o \
	$(BUILD_DIR)/asm/monolithlib/nand/code_804DA4CC.o \
	$(BUILD_DIR)/asm/monolithlib/nand/CNReqtaskSave.o \
	$(BUILD_DIR)/asm/monolithlib/nand/CNReqtaskLoad.o \
	$(BUILD_DIR)/asm/monolithlib/nand/CNReqtaskReaddir.o \
	$(BUILD_DIR)/asm/monolithlib/nand/CNReqtaskRemove.o \
	$(BUILD_DIR)/asm/monolithlib/nand/CNReqtaskCheck.o \
	$(BUILD_DIR)/asm/monolithlib/effect/CERandomizer.o \
	$(BUILD_DIR)/asm/monolithlib/code_804DB938.o \
	$(BUILD_DIR)/asm/monolithlib/work/CWorkSystemPack.o \
	$(BUILD_DIR)/asm/monolithlib/CPackItem.o \
	$(BUILD_DIR)/asm/monolithlib/CArcItem.o \
	$(BUILD_DIR)/asm/monolithlib/code_804DEDA8.o \
	$(BUILD_DIR)/asm/monolithlib/CSchedule.o \
	$(BUILD_DIR)/asm/monolithlib/code_804E36DC.o \
	$(BUILD_DIR)/asm/monolithlib/ScheduleList.o \
	$(BUILD_DIR)/asm/monolithlib/CMdlMaterial.o \
	$(BUILD_DIR)/asm/monolithlib/CMdlMouth.o \
	$(BUILD_DIR)/asm/monolithlib/CMdlAnmUV.o \
	$(BUILD_DIR)/asm/monolithlib/CMdlAnmEye.o \
	$(BUILD_DIR)/asm/monolithlib/CMdlLook.o \
	$(BUILD_DIR)/asm/monolithlib/CMdlDynamics.o \
	$(BUILD_DIR)/asm/monolithlib/code_804EE0F4.o \
	$(BUILD_DIR)/asm/monolithlib/code_804F0258.o \
	$(BUILD_DIR)/asm/monolithlib/nand/CNReqtaskSaveBanner.o \
	$(BUILD_DIR)/asm/monolithlib/nand/CNBanner.o