GAME_O_FILES :=\
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CGame.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80039EEC.o \
	$(BUILD_DIR)/asm/sdata.o \
	$(BUILD_DIR)/src/kyoshin/appgame/cf/main.o \
	$(BUILD_DIR)/asm/sdata_1.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8003A05C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8003AA00.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_800539EC.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/CfScript.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80069710.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8006A960.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80074F4C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8007C0F8.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8008753C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8008A104.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_800AA008.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_800AB3D0.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_800B9C14.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_800C2C90.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_800D7A04.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_800FEB84.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8010EA64.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801135E0.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8011C44C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8012BAD4.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8012DF90.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801414CC.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8014255C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80155660.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8015BAA8.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8016ED50.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80189DE8.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801A1864.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801A30D8.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801AFE1C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801BA14C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801BCA38.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801C189C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801C4B60.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801D1F9C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801EADC0.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_801F3410.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80201A84.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80205A7C.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8020AB80.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8021BC70.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80221E38.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_802293F0.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8023BCF0.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_802405F4.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80250D24.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8025D470.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_802744D4.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8028DCAC.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80293140.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80296898.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_80296B44.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_8029E7E4.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_802A07F4.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_802AB3B8.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_802AEB1C.o \
	$(BUILD_DIR)/src/kyoshin/appgame/cf/code_802AEB74.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_802AEBC4.o \
	$(BUILD_DIR)/asm/kyoshin/appgame/cf/code_802B48A0.o \


MW_O_FILES :=\
	$(BUILD_DIR)/asm/MetroTRK/mem_TRK.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/__mem.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/__exception.o \
	$(BUILD_DIR)/asm/sbss.o \
	$(BUILD_DIR)/src/MSL_C/PPC_EABI/Runtime/__start.o \
	$(BUILD_DIR)/asm/sbss_1.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/strlen.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/__va_arg.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/global_destructor_chain.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/NMWException.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/ptmf.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/MWRTTI.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/runtime.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/__init_cpp_exceptions.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/Gecko_ExceptionPPC.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/GCN_mem_alloc.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/alloc.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/ansi_files.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/ansi_fp.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/arith.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/buffer_io.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/direct_io.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/file_io.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/file_pos.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/mbstring.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/mem.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/mem_funcs.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/math_api.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/misc_io.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/printf.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/rand.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/scanf.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/string.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/strtold.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/strtoul.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/code_802C47D4.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/wmem.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/wprintf.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/wstring.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/wchar_io.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/uart_console_io_gcn.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common/code_802C71E8.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/math_sun.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/e_acos.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/e_asin.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/e_atan2.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/e_fmod.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/e_log.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/e_log10.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/e_pow.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/e_rem_pio2.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/k_cos.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/k_rem_pio2.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/k_sin.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/k_tan.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_atan.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_ceil.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_copysign.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_cos.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_floor.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_frexp.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_ldexp.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_modf.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_sin.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/s_tan.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/w_acos.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/w_asin.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/w_atan2.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/w_fmod.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/w_log.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/w_log10.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/w_pow.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/e_sqrt.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/math_ppc.o \
	$(BUILD_DIR)/asm/MSL_C/MSL_Common_Embedded/Math/w_sqrt.o \
	$(BUILD_DIR)/asm/MetroTRK/code_802CB46C.o \
	$(BUILD_DIR)/asm/MetroTRK/MWCriticalSection_gc.o \
	$(BUILD_DIR)/asm/MetroTRK/CircleBuffer.o \
	$(BUILD_DIR)/asm/MetroTRK/flush_cache.o \
	$(BUILD_DIR)/asm/MetroTRK/main_TRK.o \
	$(BUILD_DIR)/asm/MetroTRK/mainloop.o \
	$(BUILD_DIR)/asm/MetroTRK/code_802CBB7C.o \
	$(BUILD_DIR)/asm/MetroTRK/dolphin_trk.o \
	$(BUILD_DIR)/asm/MetroTRK/dolphin_trk_glue.o \
	$(BUILD_DIR)/asm/MetroTRK/nubinit.o \
	$(BUILD_DIR)/asm/MetroTRK/MetroTRK_802CC93C.o \
	$(BUILD_DIR)/asm/NdevExi2A/DebuggerDriver.o \
	$(BUILD_DIR)/asm/NdevExi2A/exi2.o \

RVL_SDK_O_FILES :=\
	$(BUILD_DIR)/asm/RevoSDK/ai/ai.o \
	$(BUILD_DIR)/asm/RevoSDK/arc/arc.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AX.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXAlloc.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXAux.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXCL.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXOut.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXSPB.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXVPB.o \
	$(BUILD_DIR)/asm/RevoSDK/ax/AXProf.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXReverbHi.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXReverbHiExp.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXDelayExp.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXDelayExpDpl2.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXReverbStdExp.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXReverbStdExpDpl2.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXChorusExp.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXChorusExpDpl2.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXLfoTable.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXSrcCoef.o \
	$(BUILD_DIR)/asm/RevoSDK/axfx/AXFXHooks.o \
	$(BUILD_DIR)/asm/RevoSDK/base/PPCArch.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gki_buffer.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gki_time.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gki_ppc.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hcisu_h2.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/uusb_ppc.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bte_hcisu.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bte_init.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bte_logmsg.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bte_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btu_task1.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bd.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_sys_conn.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_sys_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/ptim.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/utl.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_dm_act.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_dm_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_dm_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_dm_pm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_hh_act.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_hh_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_hh_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/bta_hh_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_acl.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_dev.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_devctl.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_discovery.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_inq.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_pm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_sco.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btm_sec.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btu_hcif.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/btu_init.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/wbt_ext.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gap_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gap_conn.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/gap_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hcicmds.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidd_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidd_conn.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidd_mgmt.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidd_pm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidh_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/hidh_conn.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_csm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_link.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/l2c_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/port_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/port_rfc.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/port_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_l2cap_if.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_mx_fsm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_port_fsm.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_port_if.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_ts_frames.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/rfc_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_api.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_db.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_discovery.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_main.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_server.o \
	$(BUILD_DIR)/asm/RevoSDK/bte/sdp_utils.o \
	$(BUILD_DIR)/asm/RevoSDK/cx/CXStreamingUncompression.o \
	$(BUILD_DIR)/asm/RevoSDK/cx/CXUncompression.o \
	$(BUILD_DIR)/asm/RevoSDK/cx/CXSecureUncompression.o \
	$(BUILD_DIR)/asm/RevoSDK/db/db.o \
	$(BUILD_DIR)/asm/RevoSDK/dsp/dsp.o \
	$(BUILD_DIR)/asm/RevoSDK/dsp/dsp_debug.o \
	$(BUILD_DIR)/asm/RevoSDK/dsp/dsp_task.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdfs.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvd.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdqueue.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvderror.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdidutils.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdFatal.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvdDeviceError.o \
	$(BUILD_DIR)/asm/RevoSDK/dvd/dvd_broadway.o \
	$(BUILD_DIR)/asm/RevoSDK/enc/encutility.o \
	$(BUILD_DIR)/asm/RevoSDK/enc/enc.o \
	$(BUILD_DIR)/asm/RevoSDK/esp.o \
	$(BUILD_DIR)/asm/RevoSDK/euart/euart.o \
	$(BUILD_DIR)/asm/RevoSDK/exi/EXIBios.o \
	$(BUILD_DIR)/asm/RevoSDK/exi/EXIUart.o \
	$(BUILD_DIR)/asm/RevoSDK/exi/EXICommon.o \
	$(BUILD_DIR)/asm/RevoSDK/fs/fs.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXInit.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXFifo.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXAttr.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXMisc.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXGeometry.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXFrameBuf.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXLight.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXTexture.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXBump.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXTev.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXPixel.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXDisplayList.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXTransform.o \
	$(BUILD_DIR)/asm/RevoSDK/gx/GXPerf.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMFrameController.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMAnmController.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMGUIManager.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMController.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMRemoteSpk.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMAxSound.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/HBMBase.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_animation.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_arcResourceAccessor.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_bounding.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_common.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_drawInfo.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_group.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_layout.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_material.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_pane.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_picture.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_resourceAccessor.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_textBox.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/lyt/lyt_window.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/math/math_triangular.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_binaryFileFormat.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_CharWriter.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_Font.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_LinkList.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_list.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_ResFont.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_ResFontBase.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_TagProcessorBase.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/nw4hbm/ut/ut_TextWriterBase.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/mix.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/syn.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synctrl.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synenv.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synmix.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synpitch.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synsample.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/synvoice.o \
	$(BUILD_DIR)/asm/RevoSDK/hbm/seq.o \
	$(BUILD_DIR)/asm/RevoSDK/ipc/ipcMain.o \
	$(BUILD_DIR)/asm/RevoSDK/ipc/ipcclt.o \
	$(BUILD_DIR)/asm/RevoSDK/ipc/memory.o \
	$(BUILD_DIR)/asm/RevoSDK/ipc/ipcProfile.o \
	$(BUILD_DIR)/asm/RevoSDK/kpad/kpad.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_heapCommon.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_expHeap.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_frameHeap.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_allocator.o \
	$(BUILD_DIR)/asm/RevoSDK/mem/mem_list.o \
	$(BUILD_DIR)/asm/RevoSDK/mix/mix.o \
	$(BUILD_DIR)/asm/RevoSDK/mix/remote.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/mtx.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/mtxvec.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/mtx44.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/vec.o \
	$(BUILD_DIR)/asm/RevoSDK/mtx/quat.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/nand.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/NANDOpenClose__103.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/NANDCore.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/NANDCheck.o \
	$(BUILD_DIR)/asm/RevoSDK/nand/NANDLogging.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OS.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSAlarm.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSAlloc.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSArena.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSAudioSystem.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSCache.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSContext.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSError.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSExec.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSFatal.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSFont.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSInterrupt.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSMessage.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSMemory.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSMutex.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSReboot.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSReset.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSRtc.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSSync.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSThread.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSTime.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSUtf.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSIpc.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSStateTM.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSPlayRecord.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSStateFlags.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSNet.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSNandbootInfo.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSPlayTime.o \
	$(BUILD_DIR)/asm/RevoSDK/crc.o \
	$(BUILD_DIR)/asm/RevoSDK/os/OSExec1.o \
	$(BUILD_DIR)/asm/MSL_C/PPC_EABI/Runtime/__ppc_eabi_init.o \
	$(BUILD_DIR)/asm/RevoSDK/pad/Pad.o \
	$(BUILD_DIR)/asm/RevoSDK/sc/scsystem.o \
	$(BUILD_DIR)/asm/RevoSDK/sc/scapi.o \
	$(BUILD_DIR)/asm/RevoSDK/sc/scapi_prdinfo.o \
	$(BUILD_DIR)/asm/RevoSDK/si/SIBios.o \
	$(BUILD_DIR)/asm/RevoSDK/si/SISamplingRate.o \
	$(BUILD_DIR)/asm/RevoSDK/tpl/TPL.o \
	$(BUILD_DIR)/asm/RevoSDK/usb/usb.o \
	$(BUILD_DIR)/asm/RevoSDK/vi/vi.o \
	$(BUILD_DIR)/asm/RevoSDK/vi/i2c.o \
	$(BUILD_DIR)/asm/RevoSDK/vi/vi3in1.o \
	$(BUILD_DIR)/asm/RevoSDK/wenc/wenc.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/WPAD.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/WPADHIDParser.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/WPADEncrypt.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/WPADMem.o \
	$(BUILD_DIR)/asm/RevoSDK/wpad/debug_msg.o \
	$(BUILD_DIR)/asm/RevoSDK/wud/wud.o \
	$(BUILD_DIR)/asm/RevoSDK/wud/WUDHidHost.o \
	$(BUILD_DIR)/asm/RevoSDK/wud/debug_msg.o

CRIWARE_O_FILES :=\
	$(BUILD_DIR)/asm/CriWare/ADXF.o \
	$(BUILD_DIR)/asm/CriWare/ADXT.o \
	$(BUILD_DIR)/asm/CriWare/AHX.o \
	$(BUILD_DIR)/asm/CriWare/LSC.o \
	$(BUILD_DIR)/asm/CriWare/MFCI.o \
	$(BUILD_DIR)/asm/CriWare/CRI_std.o \
	$(BUILD_DIR)/asm/CriWare/CFT.o \
	$(BUILD_DIR)/asm/CriWare/MWSFD.o \
	$(BUILD_DIR)/asm/CriWare/MPV.o \
	$(BUILD_DIR)/asm/CriWare/DCT.o \
	$(BUILD_DIR)/asm/CriWare/MPS.o \
	$(BUILD_DIR)/asm/CriWare/SFD.o \
	$(BUILD_DIR)/asm/CriWare/SFX.o \
	$(BUILD_DIR)/asm/CriWare/SUD.o


NW4R_O_FILES :=\
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_rescommon.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resdict.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resfile.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resmdl.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resshp.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_restev.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resmat.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resvtx.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_restex.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resnode.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanm.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmclr.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmtexpat.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmtexsrt.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmchr.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmamblight.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmlight.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmfog.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmcamera.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmscn.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_resanmshp.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmclr.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmchr.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmscn.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_obj.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_anmobj.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_gpu.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_cpu.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_state.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_draw1mat1shp.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_calcview.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_dcc.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_workmem.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_calcworld.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_draw.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_camera.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_basic.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_maya.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_xsi.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_3dsmax.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnobj.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnroot.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnmdlsmpl.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnmdl.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnmdlexpand.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_calcmaterial.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_init.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_scnproc.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_fog.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_light.o \
	$(BUILD_DIR)/asm/nw4r/g3d/g3d_calcvtx.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_init.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_pane.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_group.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_layout.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_picture.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_textBox.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_window.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_bounding.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_material.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_texMap.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_drawInfo.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_animation.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_resourceAccessor.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_arcResourceAccessor.o \
	$(BUILD_DIR)/asm/nw4r/lyt/lyt_common.o \
	$(BUILD_DIR)/asm/nw4r/math/math_arithmetic.o \
	$(BUILD_DIR)/asm/nw4r/math/math_triangular.o \
	$(BUILD_DIR)/asm/nw4r/math/math_types.o \
	$(BUILD_DIR)/asm/nw4r/math/math_geometry.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_AxManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_AxVoice.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_AxVoiceManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_AxfxImpl.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Bank.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_BankFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_BasicPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_BasicSound.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_BiquadFilterPreset.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Channel.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_DisposeCallbackManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_EnvGenerator.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_ExternalSoundPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_FxChorusDpl2.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_FxDelayDpl2.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_FxReverbStdDpl2.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_InstancePool.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Lfo.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MemorySoundArchive.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MidiSeqPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MmlParser.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MmlSeqTrack.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_MmlSeqTrackAllocator.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_NandSoundArchive.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_RemoteSpeaker.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_RemoteSpeakerManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqSound.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqSoundHandle.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SeqTrack.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundArchive.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundArchiveFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundArchivePlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundHandle.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundStartable.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundSystem.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_SoundThread.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmChannel.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmSound.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_StrmSoundHandle.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Task.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_TaskManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_TaskThread.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Voice.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_VoiceManager.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_Util.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WaveFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WaveSound.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WaveSoundHandle.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WsdFile.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_WsdPlayer.o \
	$(BUILD_DIR)/asm/nw4r/snd/snd_adpcm.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_LinkList.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_CharStrmReader.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_IOStream.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_FileStream.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_LockedCache.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_Font.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_ResFontBase.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_ResFont.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_ArchiveFontBase.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_PackedFont.o \
	$(BUILD_DIR)/asm/nw4r/ut/ut_CharWriter.o

MONOLITHLIB_O_FILES :=\
	$(BUILD_DIR)/asm/monolithlib/code_80432678.o \
	$(BUILD_DIR)/asm/monolithlib/code_80435D28.o \
	$(BUILD_DIR)/asm/monolithlib/code_80435DF8.o \
	$(BUILD_DIR)/asm/monolithlib/code_80435E70.o \
	$(BUILD_DIR)/asm/monolithlib/code_80436138.o \
	$(BUILD_DIR)/asm/monolithlib/code_80436260.o \
	$(BUILD_DIR)/asm/monolithlib/code_80436E84.o \
	$(BUILD_DIR)/asm/monolithlib/code_80436F20.o \
	$(BUILD_DIR)/asm/monolithlib/code_8043738C.o \
	$(BUILD_DIR)/asm/monolithlib/code_8043FBC4.o \
	$(BUILD_DIR)/asm/monolithlib/code_80444418.o \
	$(BUILD_DIR)/asm/monolithlib/code_80446538.o \
	$(BUILD_DIR)/asm/monolithlib/code_80448F30.o \
	$(BUILD_DIR)/asm/monolithlib/code_8044DB24.o \
	$(BUILD_DIR)/src/monolithlib/code_80450B14.o \
	$(BUILD_DIR)/asm/monolithlib/code_80450B2C.o \
	$(BUILD_DIR)/asm/monolithlib/code_80450B44.o \
	$(BUILD_DIR)/asm/monolithlib/code_804645CC.o \
	$(BUILD_DIR)/asm/monolithlib/code_80468434.o \
	$(BUILD_DIR)/asm/monolithlib/code_8046A530.o \
	$(BUILD_DIR)/asm/monolithlib/code_80474F80.o \
	$(BUILD_DIR)/asm/monolithlib/code_8047CA88.o \
	$(BUILD_DIR)/asm/monolithlib/code_8047D2AC.o \
	$(BUILD_DIR)/asm/monolithlib/code_80481E6C.o \
	$(BUILD_DIR)/asm/monolithlib/code_8048EAA8.o \
	$(BUILD_DIR)/asm/monolithlib/code_8049431C.o \
	$(BUILD_DIR)/asm/monolithlib/code_8049FCAC.o \
	$(BUILD_DIR)/asm/monolithlib/code_804B2578.o \
	$(BUILD_DIR)/asm/monolithlib/code_804B2FF0.o \
	$(BUILD_DIR)/asm/monolithlib/code_804B59C8.o \
	$(BUILD_DIR)/asm/monolithlib/code_804BAE10.o \
	$(BUILD_DIR)/asm/monolithlib/code_804BC9EC.o \
	$(BUILD_DIR)/asm/monolithlib/code_804BD8E8.o \
	$(BUILD_DIR)/asm/monolithlib/code_804BF59C.o \
	$(BUILD_DIR)/asm/monolithlib/code_804C8684.o \
	$(BUILD_DIR)/asm/monolithlib/code_804C8718.o \
	$(BUILD_DIR)/asm/monolithlib/code_804CC2B8.o \
	$(BUILD_DIR)/asm/monolithlib/code_804DA4CC.o \
	$(BUILD_DIR)/asm/monolithlib/code_804DAF70.o \
	$(BUILD_DIR)/asm/monolithlib/code_804DB0F0.o \
	$(BUILD_DIR)/asm/monolithlib/code_804DB240.o \
	$(BUILD_DIR)/asm/monolithlib/code_804DB348.o \
	$(BUILD_DIR)/asm/monolithlib/code_804DB438.o \
	$(BUILD_DIR)/asm/monolithlib/code_804DB938.o \
	$(BUILD_DIR)/asm/monolithlib/code_804F0258.o \
	$(BUILD_DIR)/asm/monolithlib/code_804F5158.o

EXTAB_O_FILES :=\
	$(BUILD_DIR)/asm/extab.o

EXTABINDEX_O_FILES :=\
	$(BUILD_DIR)/asm/extabindex.o

CTORS_O_FILES :=\
	$(BUILD_DIR)/asm/ctors.o

RODATA_O_FILES :=\
	$(BUILD_DIR)/asm/rodata.o

DATA_O_FILES :=\
	$(BUILD_DIR)/asm/data.o

BSS_O_FILES :=\
	$(BUILD_DIR)/asm/bss.o

SDATA2_O_FILES :=\
	$(BUILD_DIR)/asm/sdata2.o

SBSS2_O_FILES :=\
	$(BUILD_DIR)/asm/sbss2.o