ADX_FILES :=\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxf/adx_fini.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxf/adx_fs.o\
	$(BUILD_DIR)/libs/CriWare/src/adx/adxf/adx_fcch.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_fsvr.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_inis.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_lsc.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_mng.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_sfa.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_sjd.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_stmc.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_tlk2.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_tlk.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_tsvr.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_xpnd.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_amp.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_bahx.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_baif.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_bsc.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_bwav.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/code_80389300.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_crs.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_dcd5.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_dcd.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_errs.o\
	$(BUILD_DIR)/libs/CriWare/src/adx/ahx/ahx_ftbl.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/ahx_link.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/ahx_mflt_c.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/ahx_mwin2_c.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/ahx_sbf2.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/ahx_sbf.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/ahx_sjd.o\
	$(BUILD_DIR)/libs/CriWare/src/adx/ahx/ahx_wtbl.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/adx_hdr.o\
	$(BUILD_DIR)/libs/CriWare/src/adx/ahx/ahx_atbl.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/ahx_bsr.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/ahx_cmn.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/ahx/ahx_dcd.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/cricfg/cfg_lib.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/cvfs/cri_cvfs.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/gcci/gcci.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/gcci/gcci_sub.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/lsc/lsc_err.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/lsc/lsc_ini.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/lsc/lsc_svr.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/lsc/lsc.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/lsc/lsc_crs.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/mfci/mfci.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/sj/sj_mem.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/sj/sj_rbf.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/sj/sj_uni.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/sj/sj_utl.o\
	$(BUILD_DIR)/libs/CriWare/src/adx/sj/sj_crs.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/sj/sj_err.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/svm/svm.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_bsps.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_bau.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/adx_dcd3.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/wiirna/rna_crs.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/wiirna/rna_err.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/wiirna/ax_rna.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/srcwii/adx_mwii.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/srcwii/adx_suwii.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/adxt/srcwii/adx_rnawii.o\
	$(BUILD_DIR)/libs/CriWare/asm/adx/std/cri_crw_std.o\

#Criware uses GC 3.0 (maybe)
$(ADX_FILES): MWCC_VERSION := 3.0
$(ADX_FILES): CONSOLE := GC

DEPENDS += $(ADX_FILES:.o=.d)

$(BUILD_DIR)/libs/CriWare/src/adx/libadxwii.a: $(ADX_FILES)
	@echo Linking... $@
	$(QUIET) mkdir -p $(dir $@)
	@echo $(ADX_FILES) > build/ADX_ofiles
	$(QUIET) $(LD) -library $(LIBRARY_LDFLAGS) -o $@ -lcf ldscript.lcf @build/ADX_ofiles
