MW_FILES:=\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/__mem.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/__exception.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/strlen.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/__va_arg.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/global_destructor_chain.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/NMWException.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/ptmf.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/MWRTTI.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/runtime.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/__init_cpp_exceptions.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/Runtime/Gecko_ExceptionPPC.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/GCN_mem_alloc.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/alloc.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/ansi_files.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/ansi_fp.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/arith.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/assert.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/buffer_io.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/direct_io.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/errno.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/file_io.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/file_pos.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/mbstring.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/mem.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/mem_funcs.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/math_api.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/misc_io.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/printf.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/rand.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/float.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/scanf.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/signal.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/string.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/strtold.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/strtoul.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wcstoul.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wmem.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wprintf.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wscanf.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wstring.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/wchar_io.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/PPC_EABI/uart_console_io_gcn.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/PPC_EABI/abort_exit_ppc_eabi.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/math_double.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/math_sun.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_acos.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_asin.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_atan2.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_fmod.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_log.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_log10.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_pow.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_rem_pio2.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/k_cos.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/k_rem_pio2.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/k_sin.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/k_tan.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_atan.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_ceil.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_copysign.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_cos.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_floor.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_frexp.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_ldexp.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_modf.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_sin.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/s_tan.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_acos.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_asin.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_atan2.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_fmod.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_log.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_log10.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_pow.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/e_sqrt.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/PPC_EABI/math_ppc.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common_Embedded/Math/w_sqrt.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MSL_C/MSL_Common/extras.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/targsupp.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/main.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/custconn/MWCriticalSection_gc.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/custconn/CircleBuffer.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/flush_cache.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/main_TRK.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/mainloop.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/mem_TRK.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MetroTRK/dispatch.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/dolphin_trk.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/dolphin_trk_glue.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/notify.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/nubevent.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/nubinit.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/serpoll.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/string_TRK.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/support.o\
	$(BUILD_DIR)/src/PowerPC_EABI_Support/MetroTRK/targcont.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/mpc_7xx_603e.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/msg.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/msgbuf.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/msghndlr.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/mslsupp.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/targimpl.o\
	$(BUILD_DIR)/asm/PowerPC_EABI_Support/MetroTRK/target_options.o\

$(MW_O_FILES): CFLAGS += -Cpp_exceptions off -inline on -str pool,readonly,reuse

#strcpy needs O4,s
$(BUILD_DIR)/src/PowerPC_EABI_Support/MSL_C/MSL_Common/string.o: CFLAGS = -use_lmw_stmw on -inline on -proc gekko -fp hard -O4,s -str pool,readonly,reuse -func_align 4 $(INCLUDES)

#Runtime has exceptions turned on for 3 specific files
$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/%.o: CFLAGS = -Cpp_exceptions off -use_lmw_stmw on -inline on -proc gekko -fp hard -O4,p -str pool,readonly,reuse -func_align 4 $(INCLUDES)
$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/NMWException.o: CFLAGS += -Cpp_exceptions on
$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/MWRTTI.o: CFLAGS += -Cpp_exceptions on
$(BUILD_DIR)/src/PowerPC_EABI_Support/Runtime/Gecko_ExceptionPPC.o: CFLAGS += -Cpp_exceptions on

DEPENDS += $(MW_FILES:.o=.d)

$(BUILD_DIR)/src/PowerPC_EABI_Support/PowerPC_EABI_Support.a: $(MW_FILES)
	@echo Linking... $@
	$(QUIET) mkdir -p $(dir $@)
	@echo $(MW_FILES) > build/MW_ofiles
	$(QUIET) $(LD) -library $(LIBRARY_LDFLAGS) -o $@ -lcf ldscript.lcf @build/MW_ofiles