BTE_FILES:=\
	$(BUILD_DIR)/asm/RevoSDK/bte/gki/gki_buffer.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/gki/gki_time.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/gki/gki_ppc.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/hci/hcisu_h2.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/hci/uusb_ppc.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/dm/bta_dm_cfg.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/hh/bta_hh_cfg.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/sys/bta_sys_cfg.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/main/bte_hcisu.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/main/bte_init.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/main/bte_logmsg.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/main/bte_main.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/main/btu_task1.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/sys/bd.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/sys/bta_sys_conn.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/sys/bta_sys_main.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/sys/ptim.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/sys/utl.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/dm/bta_dm_act.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/dm/bta_dm_api.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/dm/bta_dm_main.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/dm/bta_dm_pm.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/hh/bta_hh_act.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/hh/bta_hh_api.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/hh/bta_hh_main.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/bta/hh/bta_hh_utils.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btm/btm_acl.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btm/btm_dev.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btm/btm_devctl.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btm/btm_discovery.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btm/btm_inq.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btm/btm_main.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btm/btm_pm.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btm/btm_sco.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btm/btm_sec.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btu/btu_hcif.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/btu/btu_init.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/wbt/wbt_ext.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/gap/gap_api.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/gap/gap_conn.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/gap/gap_utils.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/hcic/hcicmds.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/hid/hidd_api.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/hid/hidd_conn.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/hid/hidd_mgmt.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/hid/hidd_pm.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/hid/hidh_api.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/hid/hidh_conn.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/l2cap/l2c_api.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/l2cap/l2c_csm.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/l2cap/l2c_link.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/l2cap/l2c_main.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/l2cap/l2c_utils.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/rfcomm/port_api.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/rfcomm/port_rfc.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/rfcomm/port_utils.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/rfcomm/rfc_l2cap_if.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/rfcomm/rfc_mx_fsm.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/rfcomm/rfc_port_fsm.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/rfcomm/rfc_port_if.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/rfcomm/rfc_ts_frames.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/rfcomm/rfc_utils.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/sdp/sdp_api.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/sdp/sdp_db.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/sdp/sdp_discovery.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/sdp/sdp_main.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/sdp/sdp_server.o\
	$(BUILD_DIR)/asm/RevoSDK/bte/stack/sdp/sdp_utils.o\

DEPENDS += $(BTE_FILES:.o=.d)

$(BUILD_DIR)/src/RevoSDK/bte/bte.a: $(BTE_FILES)
	@echo Linking... $@
	$(QUIET) mkdir -p $(dir $@)
	@echo $(BTE_FILES) > build/BTE_ofiles
	$(QUIET) $(LD) -library $(LIBRARY_LDFLAGS) -o $@ -lcf ldscript.lcf @build/BTE_ofiles
