MSLC_FILES:=\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/alloc.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/ansi_files.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/ansi_fp.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/arith.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/assert.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/buffer_io.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/ctype.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/direct_io.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/errno.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/file_io.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/FILE_POS.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/locale.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/mbstring.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/mem.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/mem_funcs.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/math_api.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/misc_io.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/printf.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/rand.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/float.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/scanf.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/signal.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/string.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/strtold.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/strtoul.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/wcstoul.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/wctype.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/wmem.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/wprintf.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/wscanf.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/wstring.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/wchar_io.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/PPC_EABI/uart_console_io_gcn.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/PPC_EABI/abort_exit_ppc_eabi.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/secure_error.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/math_double.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/math_sun.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_acos.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_asin.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_atan2.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_fmod.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_log.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_log10.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_pow.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_rem_pio2.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_cos.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_rem_pio2.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_sin.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_tan.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_atan.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_ceil.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_copysign.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_cos.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_floor.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_frexp.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_ldexp.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_modf.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_sin.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_tan.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_acos.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_asin.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_atan2.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_fmod.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_log.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_log10.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_pow.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_sqrt.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/PPC_EABI/math_ppc.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_sqrt.o\
	$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_Common/extras.o\

DEPENDS += $(MSLC_FILES:.o=.d)

$(MSLC_FILES): CFLAGS += -Cpp_exceptions off -inline on -str pool,readonly,reuse -ipa file

$(BUILD_DIR)/libs/PowerPC_EABI_Support/src/MSL_C/MSL_C.PPCEABI.bare.H.a: $(MSLC_FILES)
	@echo Linking... $@
	$(QUIET) mkdir -p $(dir $@)
	@echo $(MSLC_FILES) > build/MSLC_ofiles
	$(QUIET) $(LD) -library $(LIBRARY_LDFLAGS) -o $@ -lcf ldscript.lcf @build/MSLC_ofiles
