#pragma once

#include <monolib/work/CEventFile.hpp>
#include <monolib/work/CMsgParam.hpp>
#include <monolib/work/CProc.hpp>
#include <monolib/work/CTTask.hpp>
#include <monolib/work/CWorkControl.hpp>
#include <monolib/work/CWorkFlowSetup.hpp>
#include <monolib/work/CWorkFlowShutdownAll.hpp>
#include <monolib/work/CWorkFlowWiiMenu.hpp>
#include <monolib/work/CWorkFlowWiiPowerOff.hpp>
#include <monolib/work/CWorkFlowWiiReset.hpp>
#include <monolib/work/CWorkRoot.hpp>
#include <monolib/work/CWorkSystem.hpp>
#include <monolib/work/CWorkSystemPack.hpp>
#include <monolib/work/CWorkThread.hpp>
#include <monolib/work/CWorkThreadSystem.hpp>
#include <monolib/work/CWorkUtil.hpp>
#include <monolib/work/IWorkEvent.hpp>
