name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    env:
      WINEPREFIX: ${{github.workspace}}/.wine
    steps:
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get -y install build-essential wine32
        sudo chown $(whoami) "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
    - name: Download compilers
      run: |
        curl -L https://cdn.discordapp.com/attachments/727918646525165659/917185027656286218/GC_WII_COMPILERS.zip \
          | bsdtar -xvf- -C tools
    - name: Build
      run: make -j$(nproc) MAPGENFLAG=1
    - name: Upload map
      uses: actions/upload-artifact@v2
      with:
        name: xenoblade.jp.MAP
        path: build/*/xenoblade.jp.MAP
